services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taskforge_api
    ports:
      - '8001:8001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgresql://taskforge:taskforge@postgres:5432/taskforge
      POSTGRES_SSL: 'false'
      POSTGRES_SYNCHRONIZE: 'false'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - taskforge_network

  postgres:
    image: postgres:18.6-alpine
    container_name: taskforge_postgres
    ports:
      - '54329:5432'
    environment:
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforge
      POSTGRES_DB: taskforge
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U taskforge -d taskforge']
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - taskforge_network

  redis:
    image: redis:7.4-alpine
    container_name: taskforge_redis
    ports:
      - '6379:6379'
    networks:
      - taskforge_network

volumes:
  postgres_data:

networks:
  taskforge_network:
    driver: bridge
