import assert from 'node:assert/strict';
import { handleDevMockRbac } from '../utils/devMockRbac.js';

const request = (path, method = 'get', data, organization = 'org-role-test') => handleDevMockRbac({ url: `/api/organizations/${organization}/${path}`, method, data });
const permissions = ['org.members.read', 'org.members.invite'];
const owner = request('roles').data.find((role) => role.isProtected);
assert.equal(request(`roles/${owner.id}/permissions`, 'put', { expectedVersion: 1, permissionCodes: [] }).error.status, 409);
assert.equal(request('roles', 'post', { name: 'Bad', permissionCodes: ['org.roles.manage'] }).error.status, 400);
const hr = request('roles', 'post', { name: ' HR ', description: 'Recruiting', permissionCodes: permissions }).data;
assert.equal(hr.name, 'HR');
assert.equal(request('roles', 'post', { name: 'hr', permissionCodes: [] }).error.status, 409);
assert.equal(request('roles', 'get', undefined, 'other-org').data.some((role) => role.name === 'HR'), false);
assert.equal(request('members/u-dev-1/role', 'patch', { roleId: hr.id }).error.status, 409);
assert.equal(request('members/u-dev-2/role', 'patch', { roleId: owner.id }).error.status, 409);
assert.equal(request('members/u-dev-2/role', 'patch', { roleId: hr.id }).data.membershipCount, 1);
assert.equal(request('members').data.find((member) => member.userId === 'u-dev-2').roleName, 'HR');
assert.equal(request(`roles/${hr.id}/archive`, 'post', { expectedVersion: 1 }).error.status, 409);
const changed = request(`roles/${hr.id}/permissions`, 'put', { expectedVersion: 1, permissionCodes: ['org.members.read'] }).data;
assert.equal(changed.version, 2);
assert.equal(request(`roles/${hr.id}/permissions`, 'put', { expectedVersion: 1, permissionCodes: [] }).error.status, 409);
assert.equal(request(`roles/${hr.id}/permissions`, 'put', { expectedVersion: 2, permissionCodes: ['org.members.read'] }).data.version, 2);
const renamed = request(`roles/${hr.id}`, 'patch', { expectedVersion: 2, name: 'People', description: 'People ops' }).data;
assert.equal(renamed.version, 3);
assert.equal(request('members').data.find((member) => member.userId === 'u-dev-2').roleName, 'People');
const invitation = request('invitations', 'post', { email: 'new@example.com', roleId: hr.id, expiresAt: '2026-12-01T00:00:00.000Z' }).data;
assert.equal(request('invitations').data[0].roleName, 'People');
const member = request('roles').data.find((role) => role.systemCode === 'MEMBER');
request('members/u-dev-2/role', 'patch', { roleId: member.id });
assert.equal(request(`roles/${hr.id}/archive`, 'post', { expectedVersion: 3 }).error.status, 409);
request(`invitations/${invitation.id}`, 'delete');
assert.ok(request(`roles/${hr.id}/archive`, 'post', { expectedVersion: 3 }).data.archivedAt);
assert.equal(request('invitation-roles').data.some((role) => role.id === hr.id), false);
assert.equal(request('invitations', 'post', { email: 'new@example.com', roleId: hr.id }).error.status, 409);
assert.equal(request('members/u-dev-3/role', 'patch', { roleId: hr.id }).error.status, 409);
request('members/u-dev-2/suspend', 'post');
assert.equal(request('members/u-dev-2/role', 'patch', { roleId: member.id }).error.status, 409);
const otherMember = request('roles').data.find((role) => role.systemCode === 'ADMIN');
assert.equal(request(`roles/${otherMember.id}`, 'patch', { expectedVersion: 1, name: 'Rename', description: '' }).error.status, 409);
assert.equal(request(`roles/${otherMember.id}/permissions`, 'put', { expectedVersion: 1, permissionCodes: [] }).data.permissionCodes.length, 0);
console.log('organization-role-management.test.js passed (role lifecycle, version conflicts, protected defaults, tenant isolation, assignment and invitation usage)');
