import { BadRequestException, ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { IsNull, type EntityManager } from 'typeorm';
import { PostgresTransactionRunner } from '../../../database/transaction-runner';
import type { PostgresProjectActor } from './project.service';
import { ProjectModuleCode, ProjectRole, ProjectState } from '../persistence/typeorm/project.entities';
import { PostgresProjectMembershipRepository, PostgresProjectModuleSettingRepository, PostgresProjectRepository } from '../persistence/typeorm/project.repositories';
import { DocumentEntity } from '../persistence/typeorm/optional-module.entities';
import { PostgresDocumentRepository } from '../persistence/typeorm/optional-module.repositories';
import { writePostgresActivity } from '../../collaboration/application/activity.writer';
import { writePostgresAudit } from '../../collaboration/application/audit.writer';
export interface DocumentInput { title: string; content: string; }
export class PostgresDocumentService {
  constructor(private readonly transactions: PostgresTransactionRunner) {}
  list(actor: PostgresProjectActor, projectId: string) { return this.transactions.run(async m => { await this.member(m, actor, projectId); return m.getRepository(DocumentEntity).find({ where: { organizationId: actor.organizationId, projectId, archivedAt: IsNull() }, order: { updatedAt: 'DESC' } }); }); }
  get(actor: PostgresProjectActor, projectId: string, id: string) { return this.transactions.run(async m => { await this.member(m, actor, projectId); return this.document(m, actor.organizationId, projectId, id); }); }
  create(actor: PostgresProjectActor, projectId: string, input: DocumentInput) { return this.transactions.run(async m => { const member = await this.mutable(m, actor, projectId); const repo = new PostgresDocumentRepository(m); const saved = await repo.save(repo.create({ organizationId: actor.organizationId, projectId, title: text(input.title, 'Document title'), content: text(input.content, 'Document content'), authorProjectMembershipId: member.id, lastEditedByProjectMembershipId: member.id, archivedAt: null })); await writePostgresActivity(m, { organizationId: actor.organizationId, projectId, actorMembershipId: actor.membershipId, actionCode: 'DOCUMENT_CREATED', subjectType: 'DOCUMENT', subjectId: saved.id }); await writePostgresAudit(m, { organizationId: actor.organizationId, projectId, actorMembershipId: actor.membershipId, actionCode: 'DOCUMENT_CREATED', targetType: 'DOCUMENT', targetId: saved.id, afterData: { title: saved.title } }); return saved; }); }
  update(actor: PostgresProjectActor, projectId: string, id: string, input: Partial<DocumentInput>) { if (Object.values(input).every(v => v === undefined)) throw new BadRequestException('At least one Document field is required'); return this.transactions.run(async m => { const member = await this.mutable(m, actor, projectId); const doc = await this.document(m, actor.organizationId, projectId, id); if (doc.archivedAt) throw new ConflictException('Archived Document is read-only'); if (doc.authorProjectMembershipId !== member.id && member.role !== ProjectRole.PROJECT_MANAGER) throw new ForbiddenException('Only the Document author or an active Project Manager may edit'); if (input.title !== undefined) doc.title = text(input.title, 'Document title'); if (input.content !== undefined) doc.content = text(input.content, 'Document content'); doc.lastEditedByProjectMembershipId = member.id; const saved = await new PostgresDocumentRepository(m).save(doc); await writePostgresActivity(m, { organizationId: actor.organizationId, projectId, actorMembershipId: actor.membershipId, actionCode: 'DOCUMENT_UPDATED', subjectType: 'DOCUMENT', subjectId: saved.id }); await writePostgresAudit(m, { organizationId: actor.organizationId, projectId, actorMembershipId: actor.membershipId, actionCode: 'DOCUMENT_UPDATED', targetType: 'DOCUMENT', targetId: saved.id, afterData: { title: saved.title } }); return saved; }); }
  archive(actor: PostgresProjectActor, projectId: string, id: string) { return this.transactions.run(async m => { const member = await this.mutable(m, actor, projectId); const doc = await this.document(m, actor.organizationId, projectId, id); if (doc.authorProjectMembershipId !== member.id && member.role !== ProjectRole.PROJECT_MANAGER) throw new ForbiddenException('Only the Document author or an active Project Manager may archive'); if (!doc.archivedAt) { doc.archivedAt = new Date(); doc.lastEditedByProjectMembershipId = member.id; } const saved = await new PostgresDocumentRepository(m).save(doc); await writePostgresActivity(m, { organizationId: actor.organizationId, projectId, actorMembershipId: actor.membershipId, actionCode: 'DOCUMENT_ARCHIVED', subjectType: 'DOCUMENT', subjectId: saved.id }); await writePostgresAudit(m, { organizationId: actor.organizationId, projectId, actorMembershipId: actor.membershipId, actionCode: 'DOCUMENT_ARCHIVED', targetType: 'DOCUMENT', targetId: saved.id }); return saved; }); }
  private async document(m: EntityManager, org: string, project: string, id: string) { const doc = await new PostgresDocumentRepository(m).findByIdForUpdate(org, project, id); if (!doc) throw new NotFoundException('Document not found'); return doc; }
  private async member(m: EntityManager, actor: PostgresProjectActor, projectId: string) { const project = await new PostgresProjectRepository(m).findByIdForUpdate(actor.organizationId, projectId); if (!project) throw new NotFoundException('Project not found'); const member = await new PostgresProjectMembershipRepository(m).findActiveByProjectAndOrganizationMembershipForUpdate(actor.organizationId, projectId, actor.membershipId); if (!member) throw new ForbiddenException('Active Project membership is required'); return { project, member }; }
  private async mutable(m: EntityManager, actor: PostgresProjectActor, projectId: string) { const { project, member } = await this.member(m, actor, projectId); if (project.state === ProjectState.COMPLETED || project.state === ProjectState.ARCHIVED) throw new ConflictException('Completed and archived projects are read-only'); const setting = await new PostgresProjectModuleSettingRepository(m).findByProjectAndCodeForUpdate(actor.organizationId, projectId, ProjectModuleCode.DOCUMENTS); if (!setting?.enabled) throw new ConflictException('Project module is disabled'); return member; }
}
function text(value: string, label: string) { const out = value?.trim(); if (!out) throw new BadRequestException(`${label} is required`); return out; }
